name: Deploy Reports
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: make install

      - name: Configure Datapane
        run: |
          make disable-analytics
          make login
        env:
          DATAPANE_TOKEN: ${{ secrets.DATAPANE_TOKEN }}

      - name: Run + Deploy Reports
        run: |
          make reports
